### ISSUE TITLE
About the open source 

### ISSUE THREAD

**Issue by zhangxujinsh** [OpenTiansong/HDhuman#1]
@OpenTiansong 
     Thanks for your geat job!   I am very interested in this idea, and want to learn it from the souce code!  
      Looking forward to the source code !

Thank you

Bob

**Comment by YrralH** [comment]
Happy to hear that and sorry for the delay. For some reason, the code is a mess and needs cleaning. We plan to offer the rendering part quickly (about in 2 months perhaps using the time of the spring festival) and we need more time to prepare the full version. BTW you can ask anything about the paper here.

**Comment by YrralH** [comment]
The code is updated now. 🙂
